// Auto-generated by scripts/generate_firmware_data.py — do not edit by hand.
// Single source of truth for audio/model params (see export_manifest.json).
#ifndef CRY_GATE_PARAMS_H_
#define CRY_GATE_PARAMS_H_

#define CRY_GATE_SR             16000
#define CRY_GATE_DURATION_S      10.0f
#define CRY_GATE_N_SAMPLES       160000
#define CRY_GATE_N_MEL           128
#define CRY_GATE_N_FFT           2048
#define CRY_GATE_HOP_LENGTH      512
#define CRY_GATE_FMIN            50
#define CRY_GATE_FMAX            7500
#define CRY_GATE_TARGET_T        313
#define CRY_GATE_THRESHOLD       0.34f

#endif  // CRY_GATE_PARAMS_H_
