// Auto-generated by scripts/generate_firmware_data.py — do not edit by hand.
// Source: edge_models/binary_cry_cnn_int8.tflite (802168 bytes)
#ifndef CRY_GATE_MODEL_DATA_H_
#define CRY_GATE_MODEL_DATA_H_

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char g_cry_gate_model[];
extern const unsigned int g_cry_gate_model_len;

#ifdef __cplusplus
}
#endif

#endif  // CRY_GATE_MODEL_DATA_H_
